
SELECT
TABLE_NAME,
  COLUMN_NAME,
  CONSTRAINT_NAME,   -- <<-- the one you want! 
  REFERENCED_TABLE_NAME,
  REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  TABLE_SCHEMA = 'allotmentdb' AND CONSTRAINT_NAME <> 'PRIMARY';

SELECT
*
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE